# Generated by Django 2.2.5 on 2019-12-09 20:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                default="{Teste}",
                size=None,
            ),
            preserve_default=False,
        )
    ]
