import { apiTypes } from '../utils';

export const WORKER_TYPES = {
  JOB_REGISTER: apiTypes('JOB_REGISTER'),
  JOB_FETCH: apiTypes('JOB_FETCH'),
  JOB_FETCH_DETAIL: apiTypes('JOB_FETCH_DETAIL'),
  JOB_UPDATE: apiTypes('JOB_UPDATE'),
  JOB_CLEAR: 'JOB_CLEAR',
  PORTFOLIO_CREATE: apiTypes('PORTFOLIO_CREATE'),
  PORTFOLIO_FETCH: apiTypes('PORTFOLIO_FETCH'),
  CLEAN_API_ERRORS: 'WORKER_CLEAN_API_ERRORS',
  CLEAN_MESSAGES: 'WORKER_CLEAN_MESSAGES',
};
