import { apiTypes } from '../utils';

export const WORKER_TYPES = {
  JOB_REGISTER: apiTypes('JOB_REGISTER'),
  JOB_FETCH: apiTypes('JOB_FETCH'),
  CUSTOMER_FETCH: apiTypes('CUSTOMER_FETCH'),
  BILLING: apiTypes('BILLING'),
  PORTFOLIO_FETCH: apiTypes('PORTFOLIO_FETCH'),
  PORTFOLIO_UPDATE: apiTypes('PORTFOLIO_UPDATE'),
  CLEAN_API_ERRORS: 'WORKER_CLEAN_API_ERRORS',
};
