# Generated by Django 2.2.5 on 2019-10-11 19:59

from django.db import migrations, models
import django.db.models.deletion
import flowit_crm.salon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HR", "Hair"),
                            ("MK", "Make up"),
                            ("NS", "Nails"),
                            ("SC", "Skin Care"),
                            ("WX", "Waxing"),
                        ],
                        max_length=2,
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="About")),
            ],
        ),
        migrations.CreateModel(
            name="WorkerRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="WorkerService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Price"
                    ),
                ),
                ("time_spent", models.DurationField(verbose_name="Duration")),
            ],
        ),
        migrations.CreateModel(
            name="WorkerPortfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=flowit_crm.salon.models.worker_media_path,
                        verbose_name="Photo",
                    ),
                ),
                ("label", models.TextField(verbose_name="Label")),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.Worker",
                        verbose_name="Worker",
                    ),
                ),
            ],
        ),
    ]
