# Generated by Django 2.2.5 on 2019-12-02 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker_job',
            field=models.ManyToManyField(through='salon.WorkerService', to='salon.Worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salon.Salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerservice',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.Job', verbose_name='Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerservice',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.Worker', verbose_name='Worker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerrole',
            name='name',
            field=models.CharField(choices=[('HR', 'Hairstylist'), ('MK', 'Makeup Artist'), ('NS', 'Nail Professional'), ('SC', 'Esthetician'), ('WX', 'Waxer')], max_length=2, verbose_name='Name'),
        ),
    ]
