# Generated by Django 2.2.5 on 2019-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_fixing_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerservice',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
