# Generated by Django 2.2.5 on 2019-12-06 17:17

from django.db import migrations, models
import flowit_crm.salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_remove_workerportfolio_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerportfolio',
            name='photos',
        ),
        migrations.AddField(
            model_name='workerportfolio',
            name='photo',
            field=models.ImageField(default='', upload_to=flowit_crm.salon.models.worker_media_path, verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
