# Generated by Django 2.2.5 on 2019-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[]),
        migrations.AddField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Mobile Phone"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email Address"
            ),
        ),
    ]
