import { apiTypes } from '../utils';

export const CUSTOMER_TYPES = {
  JOB_FETCH: apiTypes('JOB_FETCH'),
  APPOINTMENT_FETCH: apiTypes('APPOINTMENT_FETCH'),
  APPOINTMENT_REGISTER: apiTypes('APPOINTMENT_REGISTER'),
  WORKER_FETCH: apiTypes('WORKER_FETCH'),
  CLEAN_API_ERRORS: 'CUSTOMER_CLEAN_API_ERRORS',
  CLEAN_MESSAGES: 'CUSTOMER_CLEAN_MESSAGES',
};